export { RecommendationsSection } from "./components/RecommendationsSection"
export { SkillsPage } from "./components/SkillsPage"
export { SkillsStackSection } from "./components/SkillsStackSection"
export { skillsContent } from "./content"
export { recommendations } from "./content/recommendations"
export { skillItems } from "./content/skills"
export { useSkillsViewModel } from "./hooks/useSkillsViewModel"
export type { Recommendation, SkillItem } from "./types"
