export * from "./components"
export { skillsContent } from "./content"
export { recommendations } from "./data/recommendations"
export { skillItems } from "./data/skills"
export type { Recommendation, SkillItem } from "./types"
